"""add simulation, scenario, workflow_event tables and task_type field

Revision ID: 3033103205d5
Revises: e945d5e45d75
Create Date: 2026-08-09 16:12:33.092250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3033103205d5'
down_revision: Union[str, None] = 'e945d5e45d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use existing enum types - don't recreate them
    # Create enum types only if they don't exist (for new ones)
    
    # Create new enum types that don't exist yet
    op.execute("CREATE TYPE scenario_status_enum AS ENUM ('PENDING', 'ACTIVE', 'COMPLETED', 'SKIPPED')")
    op.execute("CREATE TYPE simulation_status_enum AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED')")
    op.execute("CREATE TYPE task_type_enum AS ENUM ('coding', 'debugging', 'database', 'api_development', 'requirement_analysis', 'testing', 'design', 'documentation', 'decision_making')")
    op.execute("CREATE TYPE workflow_event_type_enum AS ENUM ('REQUIREMENT_CHANGE', 'DEADLINE_WARNING', 'STAKEHOLDER_MESSAGE', 'BUG_REPORT', 'PRIORITY_CHANGE')")
    op.execute("CREATE TYPE workflow_event_status_enum AS ENUM ('pending', 'acknowledged', 'resolved', 'dismissed')")
    
    op.create_table('scenarios',
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('workplace_context', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('difficulty', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='difficulty_level_enum', create_type=False), nullable=False),
    sa.Column('required_skills', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('objectives', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'COMPLETED', 'SKIPPED', name='scenario_status_enum', create_type=False), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenarios_sequence', 'scenarios', ['simulation_id', 'sequence'], unique=True)
    op.create_index('ix_scenarios_simulation_id', 'scenarios', ['simulation_id'], unique=False)
    op.create_index('ix_scenarios_status', 'scenarios', ['status'], unique=False)
    op.create_table('simulations',
    sa.Column('student_id', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('difficulty', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='difficulty_level_enum', create_type=False), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='simulation_status_enum', create_type=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_scenario_id', sa.UUID(), nullable=True),
    sa.Column('current_task_id', sa.UUID(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_scenario_id'], ['scenarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_simulations_company_id', 'simulations', ['company_id'], unique=False)
    op.create_index('ix_simulations_project_id', 'simulations', ['project_id'], unique=False)
    op.create_index('ix_simulations_status', 'simulations', ['status'], unique=False)
    op.create_index('ix_simulations_student_id', 'simulations', ['student_id'], unique=False)
    op.create_table('scenario_tasks',
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenario_tasks_scenario_id', 'scenario_tasks', ['scenario_id'], unique=False)
    op.create_index('ix_scenario_tasks_sequence', 'scenario_tasks', ['scenario_id', 'sequence'], unique=True)
    op.create_index('ix_scenario_tasks_task_id', 'scenario_tasks', ['task_id'], unique=False)
    op.create_table('workflow_events',
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.Column('event_type', postgresql.ENUM('REQUIREMENT_CHANGE', 'DEADLINE_WARNING', 'STAKEHOLDER_MESSAGE', 'BUG_REPORT', 'PRIORITY_CHANGE', name='workflow_event_type_enum', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_requirement', sa.Text(), nullable=True),
    sa.Column('updated_requirement', sa.Text(), nullable=True),
    sa.Column('trigger_condition', sa.Text(), nullable=True),
    sa.Column('action_required', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'acknowledged', 'resolved', 'dismissed', name='workflow_event_status_enum', create_type=False), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_events_occurred_at', 'workflow_events', ['occurred_at'], unique=False)
    op.create_index('ix_workflow_events_simulation_id', 'workflow_events', ['simulation_id'], unique=False)
    op.create_index('ix_workflow_events_status', 'workflow_events', ['status'], unique=False)
    op.create_index('ix_workflow_events_task_id', 'workflow_events', ['task_id'], unique=False)
    op.create_index('ix_workflow_events_type', 'workflow_events', ['event_type'], unique=False)
    op.add_column('tasks', sa.Column('task_type', postgresql.ENUM('coding', 'debugging', 'database', 'api_development', 'requirement_analysis', 'testing', 'design', 'documentation', 'decision_making', name='task_type_enum', create_type=False), nullable=False, server_default='coding'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_type')
    op.drop_index('ix_workflow_events_type', table_name='workflow_events')
    op.drop_index('ix_workflow_events_task_id', table_name='workflow_events')
    op.drop_index('ix_workflow_events_status', table_name='workflow_events')
    op.drop_index('ix_workflow_events_simulation_id', table_name='workflow_events')
    op.drop_index('ix_workflow_events_occurred_at', table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index('ix_scenario_tasks_task_id', table_name='scenario_tasks')
    op.drop_index('ix_scenario_tasks_sequence', table_name='scenario_tasks')
    op.drop_index('ix_scenario_tasks_scenario_id', table_name='scenario_tasks')
    op.drop_table('scenario_tasks')
    op.drop_index('ix_simulations_student_id', table_name='simulations')
    op.drop_index('ix_simulations_status', table_name='simulations')
    op.drop_index('ix_simulations_project_id', table_name='simulations')
    op.drop_index('ix_simulations_company_id', table_name='simulations')
    op.drop_table('simulations')
    op.drop_index('ix_scenarios_status', table_name='scenarios')
    op.drop_index('ix_scenarios_simulation_id', table_name='scenarios')
    op.drop_index('ix_scenarios_sequence', table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
    
    # Drop custom enum types (only the new ones we created)
    op.execute("DROP TYPE IF EXISTS workflow_event_status_enum")
    op.execute("DROP TYPE IF EXISTS workflow_event_type_enum")
    op.execute("DROP TYPE IF EXISTS task_type_enum")
    op.execute("DROP TYPE IF EXISTS simulation_status_enum")
    op.execute("DROP TYPE IF EXISTS scenario_status_enum")