"""add submission tables

Revision ID: af99a31f16d3
Revises: d65ed6a2bc18
Create Date: 2026-08-08 17:04:51.251232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'af99a31f16d3'
down_revision: Union[str, None] = 'd65ed6a2bc18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'REJECTED', name='submission_status_enum'), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submissions_status', 'submissions', ['status'], unique=False)
    op.create_index('ix_submissions_student_id', 'submissions', ['student_id'], unique=False)
    op.create_index('ix_submissions_task_id', 'submissions', ['task_id'], unique=False)
    op.create_table('submission_versions',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'REJECTED', name='submission_version_status_enum'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submission_versions_status', 'submission_versions', ['status'], unique=False)
    op.create_index('ix_submission_versions_submission_id', 'submission_versions', ['submission_id'], unique=False)
    op.create_index('ix_submission_versions_version_number', 'submission_versions', ['version_number'], unique=False)
    op.create_table('ai_reviews',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='ai_review_status_enum'), nullable=False),
    sa.Column('result', sa.Enum('APPROVED', 'CHANGES_REQUIRED', 'REJECTED', name='ai_review_result_enum'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='ai_review_severity_enum'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('strengths', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('risks', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('actions', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['submission_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_reviews_result', 'ai_reviews', ['result'], unique=False)
    op.create_index('ix_ai_reviews_status', 'ai_reviews', ['status'], unique=False)
    op.create_index('ix_ai_reviews_version_id', 'ai_reviews', ['version_id'], unique=False)
    op.create_table('review_history',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('previous_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='review_history_prev_status_enum'), nullable=True),
    sa.Column('new_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='review_history_new_status_enum'), nullable=False),
    sa.Column('previous_result', sa.Enum('APPROVED', 'CHANGES_REQUIRED', 'REJECTED', name='review_history_prev_result_enum'), nullable=True),
    sa.Column('new_result', sa.Enum('APPROVED', 'CHANGES_REQUIRED', 'REJECTED', name='review_history_new_result_enum'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payload_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['ai_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_history_action', 'review_history', ['action'], unique=False)
    op.create_index('ix_review_history_review_id', 'review_history', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_history_review_id', table_name='review_history')
    op.drop_index('ix_review_history_action', table_name='review_history')
    op.drop_table('review_history')
    op.drop_index('ix_ai_reviews_version_id', table_name='ai_reviews')
    op.drop_index('ix_ai_reviews_status', table_name='ai_reviews')
    op.drop_index('ix_ai_reviews_result', table_name='ai_reviews')
    op.drop_table('ai_reviews')
    op.drop_index('ix_submission_versions_version_number', table_name='submission_versions')
    op.drop_index('ix_submission_versions_submission_id', table_name='submission_versions')
    op.drop_index('ix_submission_versions_status', table_name='submission_versions')
    op.drop_table('submission_versions')
    op.drop_index('ix_submissions_task_id', table_name='submissions')
    op.drop_index('ix_submissions_student_id', table_name='submissions')
    op.drop_index('ix_submissions_status', table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
