"""initial schema

Revision ID: d65ed6a2bc18
Revises: 
Create Date: 2026-08-01 06:45:21.405610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd65ed6a2bc18'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company_type', sa.Enum('STARTUP', 'PRODUCT_COMPANY', 'MNC', 'HEALTHCARE', 'BANKING', 'ECOMMERCE', 'EDUCATION', name='company_type_enum'), nullable=False),
    sa.Column('industry', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('mission', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('student_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_company_type', 'companies', ['company_type'], unique=False)
    op.create_index('ix_companies_student_id', 'companies', ['student_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=150), nullable=False),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_logs_action', 'activity_logs', ['action'], unique=False)
    op.create_index('ix_activity_logs_company_id', 'activity_logs', ['company_id'], unique=False)
    op.create_table('managers',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('personality', sa.Enum('STRICT', 'FRIENDLY', 'CORPORATE', 'STARTUP_FOUNDER', name='manager_personality_enum'), nullable=False),
    sa.Column('satisfaction_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_managers_company_id', 'managers', ['company_id'], unique=False)
    op.create_table('messages',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.Enum('STUDENT', 'MANAGER', 'TEAM_MEMBER', 'SYSTEM', name='message_sender_type_enum'), nullable=False),
    sa.Column('sender_id', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_company_id', 'messages', ['company_id'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('TASK_ASSIGNED', 'DEADLINE_UPDATED', 'MEETING_SCHEDULED', 'REQUIREMENT_CHANGED', 'BUG_REPORTED', 'SPRINT_STARTED', 'SPRINT_COMPLETED', name='notification_type_enum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_company_id', 'notifications', ['company_id'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_table('projects',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('technology_stack', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='difficulty_level_enum'), nullable=False),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='project_status_enum'), nullable=False),
    sa.Column('objectives', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('modules', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('deliverables', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_company_id', 'projects', ['company_id'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_table('team_members',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=150), nullable=False),
    sa.Column('personality', sa.String(length=100), nullable=False),
    sa.Column('skill_level', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_team_members_company_id', 'team_members', ['company_id'], unique=False)
    op.create_table('events',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('REQUIREMENT_CHANGE', 'CLIENT_FEEDBACK', 'BUG_REPORT', 'CODE_REVIEW', 'SPRINT_PLANNING', 'SPRINT_REVIEW', 'PRODUCTION_FAILURE', 'DATABASE_CHANGE', 'SECURITY_AUDIT', 'DEADLINE_CHANGED', 'EMERGENCY_MEETING', name='event_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_event_type', 'events', ['event_type'], unique=False)
    op.create_index('ix_events_project_id', 'events', ['project_id'], unique=False)
    op.create_table('meeting_schedules',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('meeting_type', sa.Enum('DAILY_STANDUP', 'SPRINT_PLANNING', 'SPRINT_REVIEW', 'RETROSPECTIVE', 'EMERGENCY', name='meeting_type_enum'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=False),
    sa.Column('participants', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attendance', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('action_items', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meeting_schedules_project_id', 'meeting_schedules', ['project_id'], unique=False)
    op.create_index('ix_meeting_schedules_scheduled_at', 'meeting_schedules', ['scheduled_at'], unique=False)
    op.create_table('project_states',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('pending_tasks', sa.Integer(), nullable=False),
    sa.Column('avg_completion_time_hours', sa.Float(), nullable=False),
    sa.Column('missed_deadlines', sa.Integer(), nullable=False),
    sa.Column('bug_count', sa.Integer(), nullable=False),
    sa.Column('communication_frequency', sa.Integer(), nullable=False),
    sa.Column('stress_level', sa.Integer(), nullable=False),
    sa.Column('manager_satisfaction', sa.Integer(), nullable=False),
    sa.Column('team_satisfaction', sa.Integer(), nullable=False),
    sa.Column('current_sprint_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index('ix_project_states_project_id', 'project_states', ['project_id'], unique=False)
    op.create_table('sprints',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sprint_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('goal', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', name='sprint_status_enum'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sprints_project_id', 'sprints', ['project_id'], unique=False)
    op.create_index('ix_sprints_project_sprint_number', 'sprints', ['project_id', 'sprint_number'], unique=True)
    op.create_table('sprint_reviews',
    sa.Column('sprint_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('velocity_completed_points', sa.Integer(), nullable=False),
    sa.Column('manager_feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sprint_id')
    )
    op.create_index('ix_sprint_reviews_sprint_id', 'sprint_reviews', ['sprint_id'], unique=False)
    op.create_table('tasks',
    sa.Column('sprint_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='task_priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('BACKLOG', 'TODO', 'IN_PROGRESS', 'REVIEW', 'BLOCKED', 'COMPLETED', name='task_status_enum'), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('deliverable_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_deadline', 'tasks', ['deadline'], unique=False)
    op.create_index('ix_tasks_priority', 'tasks', ['priority'], unique=False)
    op.create_index('ix_tasks_sprint_id', 'tasks', ['sprint_id'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_task_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_dependencies_depends_on_task_id', 'task_dependencies', ['depends_on_task_id'], unique=False)
    op.create_index('ix_task_dependencies_task_id', 'task_dependencies', ['task_id'], unique=False)
    op.create_index('ix_task_dependencies_unique_pair', 'task_dependencies', ['task_id', 'depends_on_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_dependencies_unique_pair', table_name='task_dependencies')
    op.drop_index('ix_task_dependencies_task_id', table_name='task_dependencies')
    op.drop_index('ix_task_dependencies_depends_on_task_id', table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_sprint_id', table_name='tasks')
    op.drop_index('ix_tasks_priority', table_name='tasks')
    op.drop_index('ix_tasks_deadline', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_sprint_reviews_sprint_id', table_name='sprint_reviews')
    op.drop_table('sprint_reviews')
    op.drop_index('ix_sprints_project_sprint_number', table_name='sprints')
    op.drop_index('ix_sprints_project_id', table_name='sprints')
    op.drop_table('sprints')
    op.drop_index('ix_project_states_project_id', table_name='project_states')
    op.drop_table('project_states')
    op.drop_index('ix_meeting_schedules_scheduled_at', table_name='meeting_schedules')
    op.drop_index('ix_meeting_schedules_project_id', table_name='meeting_schedules')
    op.drop_table('meeting_schedules')
    op.drop_index('ix_events_project_id', table_name='events')
    op.drop_index('ix_events_event_type', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_team_members_company_id', table_name='team_members')
    op.drop_table('team_members')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_company_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_company_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_messages_company_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_managers_company_id', table_name='managers')
    op.drop_table('managers')
    op.drop_index('ix_activity_logs_company_id', table_name='activity_logs')
    op.drop_index('ix_activity_logs_action', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index('ix_companies_student_id', table_name='companies')
    op.drop_index('ix_companies_company_type', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
