"""add notification and event types for submission workflow

Revision ID: e945d5e45d75
Revises: 0941d7f7290b
Create Date: 2026-08-09 13:19:28.790184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e945d5e45d75'
down_revision: Union[str, None] = '0941d7f7290b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new NotificationType enum values
    op.execute("ALTER TYPE notification_type_enum ADD VALUE IF NOT EXISTS 'task_started'")
    op.execute("ALTER TYPE notification_type_enum ADD VALUE IF NOT EXISTS 'submission_received'")
    op.execute("ALTER TYPE notification_type_enum ADD VALUE IF NOT EXISTS 'review_started'")
    op.execute("ALTER TYPE notification_type_enum ADD VALUE IF NOT EXISTS 'review_completed'")
    op.execute("ALTER TYPE notification_type_enum ADD VALUE IF NOT EXISTS 'submission_approved'")
    op.execute("ALTER TYPE notification_type_enum ADD VALUE IF NOT EXISTS 'task_completed'")
    op.execute("ALTER TYPE notification_type_enum ADD VALUE IF NOT EXISTS 'dependency_blocked'")

    # Add new EventType enum values
    op.execute("ALTER TYPE event_type_enum ADD VALUE IF NOT EXISTS 'task_started'")
    op.execute("ALTER TYPE event_type_enum ADD VALUE IF NOT EXISTS 'submission_created'")
    op.execute("ALTER TYPE event_type_enum ADD VALUE IF NOT EXISTS 'submission_version_created'")
    op.execute("ALTER TYPE event_type_enum ADD VALUE IF NOT EXISTS 'review_started'")
    op.execute("ALTER TYPE event_type_enum ADD VALUE IF NOT EXISTS 'ai_review_completed'")
    op.execute("ALTER TYPE event_type_enum ADD VALUE IF NOT EXISTS 'changes_requested'")
    op.execute("ALTER TYPE event_type_enum ADD VALUE IF NOT EXISTS 'submission_resubmitted'")
    op.execute("ALTER TYPE event_type_enum ADD VALUE IF NOT EXISTS 'manager_approved'")
    op.execute("ALTER TYPE event_type_enum ADD VALUE IF NOT EXISTS 'task_completed'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='task_priority_enum'),
               nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('backlog', 'todo', 'in_progress', 'submitted', 'under_review', 'changes_requested', 'manager_approval', 'blocked', 'completed', name='task_status_enum'),
               nullable=False)
    op.create_index('ix_tasks_priority', 'tasks', ['priority'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_priority', table_name='tasks')
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('backlog', 'todo', 'in_progress', 'submitted', 'under_review', 'changes_requested', 'manager_approval', 'blocked', 'completed', name='task_status_enum'),
               nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='task_priority_enum'),
               nullable=True)
    # ### end Alembic commands ###
    
    # Note: PostgreSQL doesn't support removing enum values easily
    # In production, you'd need to recreate the enum type without the values
    # For now, we leave the enum values in place during downgrade